version: '2.3'
services:
  monitor:
    image: elastic/metricbeat:6.5.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d:ro
    #  -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    network_mode: host
    user: "root"
    command: -system.hostfs=/hostfs --strict.perms=false -e
    restart: always
